version: '3.4'

services:
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - 6379:6379

  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  discountdb:
    container_name: discountdb
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=discountdb
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  mongoclient:
    container_name: mongoclient
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - discountdb
    volumes:
      - mongoclient_data:/data/db

  pgadmin:
    container_name: pgadmin
    restart: always
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    depends_on:
      - basketdb
    volumes:
      - pgadmin_data:/root/.pgadmin

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CacheSetting:ConnectionString=basketdb:6379
    ports:
      - "8001:80"
    depends_on:
      - basketdb

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:default=mongodb://catalogdb:27017"
    ports:
      - "8000:80"
    depends_on:
      - catalogdb
  
  portainer:
    container_name: portainer
    restart: always
    ports:
      - 8080:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

