version: '3.4'

services:
  basketdb:
    image: redis:alpine  

  catalogdb:
    image: mongo

  discountdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  mongoclient:
    image: mongoclient/mongoclient

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  portainer:
    image: portainer/portainer-ce

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:
  mongoclient_data: